language: python
python:
#  - "2.6"
#  - "2.7"
#  - "pypy"
  - "pypy-5.3.1"
  - "pypy3"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -U "pytest>=3.6.0" pytest-timeout
script:
  - python -m pytest
