version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.5-stretch
    working_directory: ~/pyknock
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "dev_requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev_requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "dev_requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest
